Mail-0/Zero

components/icons/icons.tsx, components/theme/mode-toggle.tsx, components/ui/nav-user.tsx
- Kept default dark mode.
- Fixed issues in light theme.
- Added a navbar theme toggle (aligned with existing icons, using the same design library).
=> Add Theme Toggle & Fix Light Theme

components/mail/mail-list.tsx
https://www.loom.com/share/710325764e604fdd8e96f2eb755bc776?sid=91a3d6f6-f93c-483b-9573-727de5c4260e
=> Fixes #6 & #7

components/context/sidebar-context.tsx, components/ui/sidebar.tsx, lib/constants.ts, package-lock.json
**1. Refactored Component Context for Maintainability:**
Split the large context logic from the ```sidebar.tsx``` component into separate files for better readability and maintainability.
**2. Introduced Constants File for Reusability:**
Added a centralized constants file to manage reusable values to avoid duplication across the codebase, improving overall code organization.
=> chore: refactored the code for better maintainability

README.md
Not sure why the other link wasn't working, this one work tho
=> Fixed link to better auth

components/mail/mail-compose.tsx
=> feat(ui): Enhance attachment handling

components/mail/mail-display.tsx
Before
After
I didn't add any functionality, just modified the existing look. I also added a button to attach files.
=> Refined the 'reply composer' for a modern look.

components/mail/mail.tsx, components/mail/use-mail.ts
remove the mail selected in `use-mail.ts` and check for if mail is selected to show the mail view in `mail.tsx`
=> feat: unselect mail on page load

components/mail/filters.tsx, components/mail/mail.tsx
Before:
After:
Addresses the problems with issue #55.
=> Redesign search and header area

components/ui/command-menu.tsx, components/ui/command.tsx
Before/After
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/66df9cd8-c567-40c4-8e12-3c689a07d191" width="800"></td>
<td><img src="https://github.com/user-attachments/assets/741281d4-1c30-49ce-823b-57293b78b42d" width="800"></td>
</tr>
</table>
=> feat(ui): Enhance Command Menu

components/mail/mail-list.tsx
=> chore: remove unnecessary gap in collapsed mail list

components/mail/mail-list.tsx
https://github.com/user-attachments/assets/d3e6d058-a85b-4588-9f4f-81064cdc6299
Might need some extra work to save the state of the sizes of the resizable panels, but deselecting/dismissing the currently selected mail is needed I think.
=> feat: deselect/dismiss mail when clicking selected mail

components/mail/mail-display.tsx
adding attachment capabilities and display to the MailDisplay Component
=> feat: add attachment handling to mail display component

components/mail/mail-compose.tsx, components/mail/mail-display.tsx
=> Add trunication on attachments

components/ui/app-sidebar.tsx
=> feat: (ui) change junk icon from trash2 to archive-x

components/mail/mail-compose.tsx
https://www.loom.com/share/a04d9c96ccff4a97b6e1282f64bf79de?sid=62249e71-196e-40be-b53c-9811b5e6400e
=> Add tabIndex for improved accessibility in compose component

components/mail/mail-display.tsx
closes #90
I wasn't sure about adding a tooltip but didn't want to over engineer a close button so i discarded the idea
=> feat: add close button to close selected mail display

components/mail/mail.tsx
=> feat: deselect/dismiss selected mail on mobile dialog close

components/mail/filters.tsx, components/mail/mail.tsx, components/mail/use-tags.ts, components/ui/calendar.tsx, package.json, pnpm-lock.yaml
Added more advanced mail filtering, something more akin to what gmail currently has
this is only the UI, the form logic has not yet been implemented
=> feat: added more advanced filtering

components/mail/mail-compose.tsx, components/mail/mail-display.tsx
Video: https://www.loom.com/share/3dd7531b456b41268d6df19a9c299c27?sid=4e091f2d-df12-4346-ba89-61a535f42299
=> feat(ui): Add Attachments Preview

app/(full-width)/contributors/page.tsx
center charts:
fix github button view on mobile:
=> chart UI(contributors): center activity charts in card component, improve mobile responsiveness

app/(full-width)/contributors/page.tsx
Added the number of open issues to the contributors page, as I thought it would be cool to see. Also fixes some responsiveness issues on mobile.
Preview: 
Closes #104
=> feat(contributors): add open issues and fix responsiveness

.env.example, app/api/auth/early-access/route.ts, app/api/driver.ts, app/api/v1/mail/auth/[providerId]/callback/route.ts, db/index.ts, docker-compose.yaml, drizzle.config.ts, helpers/redis.ts, lib/auth-client.ts, lib/auth.ts, lib/env.ts, package.json, pnpm-lock.yaml
The env is now type safe so that devs don't have to go through debugging hell.
also, added redis and upstash proxy in docker-compose.yaml to make it easier to develop locally without a upstash account.
=> feat: type safe env

app/api/driver.ts, app/api/v1/mail/[id]/read/route.ts, components/mail/mail-list.tsx, hooks/use-threads.ts
- mark mails as read in indexdb using threads and in google api using api route.
- fixed 2 linter errors in `use-threads.ts`
=> marking mails as read when opening them in the mail-display panel

lib/env.ts
=> chore: better env validation error

components/ui/nav-user.tsx
login route broke after changing the folder name from signin to login
this fixes the issue.
=> fix login route

components/mail/mail-list.tsx, components/mail/search-bar.tsx, hooks/use-search-value.ts
Adds text highlighting functionality to the mail list when searching.
Changes:
- Added highlight functionality in mail-list component
- Updated search-bar to include highlight text in search state
- Added highlight field to search value hook
The highlighting:
- Shows matched text with dark background in light mode
- Shows matched text with light background in dark mode
- Maintains readability with contrasting colors
- Preserves case of original text while matching case-insensitively
=> feat: add search text highlighting

app/(full-width)/contributors/page.tsx
The data returned by github includes both issues and pull requests so we change the wording to reflect this.
=> fix(contributors): change wording to include prs

app/error.tsx
I have added an error.tsx file inside the app directory for the handling of unexpected client and server side errors. The UI is taken from the not-found page, so that the consistency will be maintained.
=> Adding error.tsx page for handling unexpected runtime errors

.gitignore, components/mail/empty-state.tsx, components/mail/mail-list.tsx, components/mail/mail.tsx
Adds a new component `components/mail/empty-state.tsx` which simply renders conditionally in-place of inbox messages when items.length === 0;
=> feat: add empty state component for MailList when no messages are present

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
This commit sets up a comprehensive development container with:
- Dockerfile for a robust development environment
- DevContainer JSON configuration with pre-installed tools
- Support for Bun, yarn, pnpm Node.js, NVM, and zsh
- VSCode extensions for improved developer experience
=> feat: Add development container configuration for Mail0 project

app/(routes)/mail/[folder]/page.tsx
- forgot to change the layout on the other mailboxes. all fixed now.
=> quick fix for the other mailboxes

app/(full-width)/contributors/page.tsx
- Fixing contribution stats
- Updating the charts to be more accurate
- Updated page UI
- Updated the cards design
- Added charts
=> fix: contributors page

components/ui/app-sidebar.tsx, package.json
=> chore: moved animations from framer-motion to motion/react

README.md, components/mail/mail-compose.tsx, components/mail/search-bar.tsx, components/ui/app-sidebar.tsx, components/ui/nav-main.tsx
fixed linting and formatting errors:
- README.md
- mail-compose.tsx
- search-bar.tsx
- app-sidebar.tsx
- nav-main.tsx
=> chore: lint and format files

app/(full-width)/privacy/page.tsx
=> feat: new policies

components/ui/app-sidebar.tsx
Simple enhancement to the compose button's visual style.
- Added gradient overlay for depth
- Enhanced hover transitions
- Improved light/dark consistency
- Added subtle inner shadow
```tsx
className="mt-1 h-8 w-[calc(100%)] border bg-secondary text-primary shadow shadow-black/5 hover:bg-secondary/90"
```
```tsx
className="relative isolate mt-1 h-8 w-[calc(100%)] overflow-hidden whitespace-nowrap bg-secondary text-primary shadow-[0_1px_theme(colors.white/0.07)_inset,0_1px_3px_theme(colors.black/0.05)] ring-1 ring-black/5 before:pointer-events-none before:absolute before:inset-0 before:-z-10 before:rounded-md before:bg-gradient-to-b before:from-white/20 before:opacity-50 before:transition-opacity hover:bg-secondary/90 hover:before:opacity-100 …
```
=> enhance: improve compose button visual feedback

components/ui/app-sidebar.tsx, components/ui/nav-main.tsx, components/ui/nav-user.tsx
a redo of #201, for the new app interface
=> redo: settings back button restore mail folder view for new UI

app/layout.tsx, components/ui/app-sidebar.tsx, components/ui/nav-main.tsx
The sidebar code is more sane.
Added react-scan for development so we can do more improvements as we go.
=> fix: improve sidebar code, add react-scan in dev

components/mail/mail-display.tsx, components/mail/thread-display.tsx
Hey @nizzyabi @ahmetskilinc :wave: 
made some fixes:
- show check icon onClick on "Copy email data"
- design of details popover was't align perfectly and Popover wasn't getting autoclose on onBlur
=> fix: show check icon on copy, fix in Details Popover

app/(routes)/settings/layout.tsx, app/page.tsx, components/home/hero-image.tsx, components/mail/mail.tsx, components/mail/reply-composer.tsx, components/ui/app-sidebar.tsx
fixed some colours, spacing, padding and margins on (mostly mobile stuff):
modified: app/(routes)/settings/layout.tsx
modified: components/home/hero-image.tsx
modified: components/mail/mail.tsx
modified: components/mail/reply-composer.tsx
modified: components/ui/app-sidebar.tsx
---
=> fixed some colours, spacing, padding and margins on mostly mobile stuff

README.md
I don't like typos, fixed it :)
---
N/A
N/A
N/A
N/A
---
=> Fix typos, improve phrasing, and clean up README code

actions/extractText.ts
This PR adds a action that takes in decodedBody (HTML) and spits out text only
---
- [] API Endpoints
https://github.com/user-attachments/assets/54d5a0ed-26fe-49c3-8d6d-f2b067e1e0e4
---
=> feat: extract text from mail action

components/mail/mail-list.tsx, components/ui/nav-main.tsx, config/navigation.ts
---
Remove bullet points that are not relevant. If your PR doesn't follow this template or [contributing guide](https://github.com/Mail-0/Mail-0/blob/main/.github/CONTRIBUTING.md) it will not be accepted.
---
Please provide a clear description of your changes. Include screenshots/recordings for UI changes and any relevant context.
---
---
some routes cause errors when fetching from the google api, so ive disabled these routes for now in order to stop the errors. will revisit and fix this.
another point is that archive does not exist in gmail, archiving in gmail is solely to remove an email from your inbox.
---
_By submitting this pull …
=> fixed date bug on some emails

components/mail/empty-state.tsx, components/mail/mail-list.tsx, components/mail/mail.tsx, components/mail/search-bar.tsx, hooks/use-search-value.ts
Please provide a clear description of your changes. Include screenshots/recordings for UI changes and any relevant context.
Added search filtering logic, can now search from: sender and filter inboxes, date ranges etc.
Updated UI to match the current style system
This is following #217 but since that PR was based on 'main', I decided to implement it and update the UI at the same time
---
Here is the loom showcasing the search filtering logic, it was before the UI update but it works the same: https://www.loom.com/share/8fe51241c3a74a2f9497582bb88949df
---
_By submitting this pull request, I confirm that my contribution is made under …
=> feat: added filter logic and improved search bar and filtering UI

apps/mail/actions/send.ts, apps/mail/components/create/create-email.tsx
- made create wider
- send to multiple emails
- new ui for 'to' list
---
=> improvements to create ui

apps/mail/app/(routes)/settings/appearance/page.tsx, apps/mail/app/(routes)/settings/connections/page.tsx, apps/mail/app/(routes)/settings/general/page.tsx, apps/mail/app/(routes)/settings/layout.tsx, apps/mail/app/(routes)/settings/security/page.tsx, apps/mail/app/(routes)/settings/shortcuts/page.tsx, apps/mail/components/create/create-email.tsx, apps/mail/components/icons/animated/book-text.tsx, apps/mail/components/icons/animated/check-check.tsx, apps/mail/components/icons/animated/inbox.tsx, apps/mail/components/icons/animated/keyboard.tsx, apps/mail/components/icons/animated/settings-gear.tsx, apps/mail/components/icons/animated/shield.tsx, apps/mail/components/icons/animated/users.tsx, apps/mail/components/icons/animated/x.tsx, apps/mail/components/theme/theme-switcher.tsx, apps/mail/components/ui/form.tsx, apps/mail/components/ui/nav-main.tsx, apps/mail/config/navigation.ts
=> fix: sidebar and settings page ui fixes

LICENSE, README.md
=> license update

apps/mail/components/mail/mail-list.tsx, apps/mail/components/mail/mail.tsx
Before: 
https://github.com/user-attachments/assets/d8c72e83-367c-4058-871d-766426393a37
After: fixed the vertical alignment UI inconsistencies 
---
https://github.com/user-attachments/assets/6e909f26-b177-41c8-bbe2-add474391eec
---
=> jkirubai/fix:list-vertical-align

packages/db/migrations/0018_bored_justice.sql, packages/db/migrations/meta/0018_snapshot.json, packages/db/migrations/meta/_journal.json, packages/db/src/schema.ts
make a primary key from the combination of ("plugin_id", "user_id"
=> feat: change pluginSettings to use composite primary key

apps/mail/components/ui/settings-content.tsx
=> fix: setting layout

apps/mail/lib/providers.tsx
=> ph provider

apps/mail/components/mail/reply-composer.tsx
=> Reply to right person

apps/mail/app/(auth)/login/login-client.tsx, apps/mail/components/golden.tsx, apps/mail/components/home/hero.tsx, apps/mail/components/home/navbar.tsx
=> Revert "fix: invite dialog colors #732"

apps/mail/package.json, bun.lock
Added the missing dompurify package which was causing build fails
---
---
=> fix: add missing dompurify dep

apps/server/src/routes/chat.ts
=> staging fix

apps/server/src/main.ts
Fixes: https://0email.featurebase.app/p/cannot-reply-with-error-this-context-has-no-executioncontext
---
---
=> fix: missing execution ctx

.env.example, .github/CONTRIBUTING.md, README.md
Update docs to mention how to setup and sync cloudflare stuff
---
---
=> chore: update docs to mention cloudflare sync

apps/server/package.json, apps/server/src/ctx.ts, apps/server/src/lib/auth.ts, apps/server/src/lib/driver/google.ts, apps/server/src/lib/driver/types.ts, apps/server/src/lib/driver/utils.ts, apps/server/src/lib/party.ts, apps/server/src/lib/server-utils.ts, apps/server/src/lib/utils.ts, apps/server/src/main.ts, apps/server/src/routes/chat.ts, apps/server/src/routes/mailto-handler.ts, apps/server/src/services/writing-style-service.ts, apps/server/src/trpc/index.ts, apps/server/src/trpc/routes/ai/compose.ts, apps/server/src/trpc/routes/mail.ts, apps/server/src/trpc/trpc.ts, bun.lock
The hono request context is now propagated via context storage, you can access hono context inside any function without having to pass down context via function params.
docs: https://hono.dev/docs/middleware/builtin/context-storage
---
---
=> feat: access hono context from anywhere

apps/mail/app/(routes)/mail/under-construction/[path]/page.tsx, apps/mail/app/layout.tsx, apps/mail/components/mail/mail-list.tsx, apps/mail/components/mail/mail-skeleton.tsx, apps/mail/components/mail/mail.tsx, apps/mail/components/mail/note-panel.tsx, apps/mail/components/mail/thread-display.tsx, apps/mail/components/ui/nav-main.tsx
- removes border on mobile
- adds correct theme-color
- changes vh to dvh
- correct height for empty state on mobile
=> responsive layout and mobile ui improvements

apps/mail/components/create/extensions.ts, apps/mail/vite.config.ts
Remove irrelevant novel extesions and warmup app ahead of time to fix SSR dep optimization issue
---
---
=> fix: dev server errors by warming up the app

apps/mail/app/globals.css, apps/mail/components/mail/mail-display.tsx, apps/mail/components/mail/mail-list.tsx, apps/mail/components/mail/mail.tsx
This PR implements several important changes:
1. Renamed GitHub workflow from `main.yml` to `lingo-dev.yml` and updated it to trigger on the `staging` branch instead of `main`
2. Added a new `sync-production.yml` workflow that creates automated PRs from `staging` to `main` for production deployments
3. Fixed UI issues in the mail application:
- Added `overscroll-behavior: none` to prevent unwanted scrolling behavior
- Increased AI summary font size from 12px to 15px for better readability
- Adjusted mail list thread subject width to 95% and fixed label alignment
- Modified mail layout panel sizing (35% default/min, 40% max) for better space utilization
4. Added new localization strings for spam management across all supported languages
_By submitting this pull request, I confirm that my …
=> Small changes

apps/mail/app/globals.css
Add fadeUpIn animation back
---
---
=> fix: add fadeInUp animation back for contributors page

apps/mail/app/root.tsx, apps/mail/hooks/use-connections.ts, apps/server/src/trpc/routes/connections.ts, apps/server/src/trpc/routes/settings.ts
`settings.get` and `connection.getDefault` are now public endpoints but they return default data and `null` in case of logged out users, this will fix the issue of UNAUTHORIZED logs being spammed for users who are just on homepage
---
---
=> fix: make some endpoints public and return default values

apps/mail/components/mail/mail.tsx
Add `isPro` check for auto labeling
---
---
=> fix: add pro check to autolabeling toggle
