Mail-0/Zero

- components/mail/data.tsx
- components/mail/mail-display.tsx
- components/mail/mail-list.tsx
- components/mail/mail.tsx
- added muted icon in the MailList
- added functionality to the switch
> Muted icon in Mailist and MailDisplay

- app/globals.css
- tailwind.config.ts
I assume we want to use **geist font sans serif** as a default, added variable for the mono font also, could be fun to add a feature to let load their own font from the UI.
> fix: geist font loads properly

- components/mail/mail.tsx
a quick fix for the height of the mail view
somehow reverted to this:
fixed to be like this:
> fix: height of desktop mail view, somehow got removed.

- providers/providers.tsx
prevents posthog from doing init if there is no key, otherwise there are errors in local development where people don't specify a key
Also there is no reason for most people to setup posthog in dev mode.
Edit: waiting on #39 to be merged first to fix CI issues before rebasing and merging this one
> fix: load posthog only if key is present to prevent error in dev

- components/context/sidebar-context.tsx
- tsconfig.json
- utils/cookies.ts
Fixes #26 
Correctly use the cookie value to restore the sidebar state to the user's last used state.
If there is no cookie, it will default to the `defaultOpen` prop.
I added a comment to explain why it's done in a `useEffect`.
Unfortunately there is a slight flicker of the sidebar until the onMount useEffect runs if the cookie does not match the `defaultOpen` prop.
Nextjs guards browser apis even on client components so the only safe way to access the cookie is in a useEffect.
Open to alternative if you know better
> Persist sidebar state through cookie

- components/mail/mail-list.tsx
Manually adjusting the `ScrollArea` height is a frustrating but necessary fix for now, as this pull request implements the tedious method. The issue seems to stem from the `TabList` component, and as the app grows, this approach will become increasingly unmanageable. I suggest we revisit this later—keeping the tab selector UI intact but handling the tab content display ourselves without relying on ShadCN.
> Fix: Adjusted ScrollArea height fixing the issues outlined in #60

- components/mail/filters.tsx
- components/mail/mail.tsx
Before:
After:
Experimenting with alternative search component designs. Here's the leading one.
> Experiment: refactor search component and filter

- components/mail/mail.tsx
Added `autoSaveId={"mail-panel-layout"}` to the `ResizablePanelGroup` for autosaving functionality built into shadcn `Resizable`
> feat (ui): add auto save id to panel group for auto saving layout sizes

- components/mail/mail-list.tsx
Before:
After:
This saves space and gives a more functional appearance.
> Improvement: Updated the email list look

- components/mail/mail-display.tsx
Tidied up `mail-display.tsx` but some issues explained below -
Needs some work on mobile - anybody feel free to make changes and improve:
`line-clamp-1` is annoying me and I'm not sure how to best work around this part.
> feat: add popover for security information in mail display

- components/mail/mail-compose.tsx
- components/mail/mail-display.tsx
Adds a tooltip to reveal the full name of an attachment, useful for when you have multiple files with similar names and would like to remove a spesific one.
Looks like this:
> feat(attachments): add tooltip with full filename

- components/mail/mail-compose.tsx
- components/mail/mail-display.tsx
In a previous commit by @HSp4m they removed the truncation of the filename in the attachment tooltip. This makes it looks weird when a filename is really long. Thats why I added back truncation to prevent it from looking weird!
Current: 
Now:
> fix: add filename truncation back

- app/(full-width)/connect-emails/page.tsx
- app/api/v1/mail/connections/[connectionId]/route.ts
- components/ui/nav-user.tsx
the better-auth logout function is currently strapped to the logout button on the nav sidebar. when triggered, it clears the user session even when multiple email accounts are logged in.
this introduces a `handleLogout` function to better handle the logout event.
It switches to the next account when multiple mail sessions exist and only triggers the better-auth logout when one account is left
> Fix multi account logout

- components/mail/mail-display.tsx
This PR fixes the textarea background color to properly support both light and dark themes.
Changes:
- Added `bg-[#FAFAFA]` for light theme
- Added `dark:bg-[#18181A]` for dark theme to maintain contrast
This adds proper visibility of text in for both themes.
> fix: textarea background color to match theme color

- app/(full-width)/contributors/page.tsx
- app/(routes)/settings/layout.tsx
- app/(routes)/settings/settings-navigation.tsx
- components/ui/app-sidebar.tsx
since you can navigate to each settings tab driectly from the `/mail` route sidebar and you can easily switch between tabs while in the settings page, it makes sense to change the **Back** link to the previous /mail folder before navigating to the settings route
- fixed the github button light theme ligjht theme display
> route back button on settings page back to previous mail folder 

- app/(routes)/settings/layout.tsx
- components/ui/nav-user.tsx
reference #201
The Add Email button under the account-switcher dropdown menu is another way to go into the settings page directly from the /mail route
this modification allows the settings page back button to restore the previous mail folder view if the user leaves the settings tab without adding a new email account
>  RE:refactor back button destination in settings - Add Email!!

- app/page.tsx
Hey @nizzyabi :wave: 
made small fixes in mail0.
- HeroImage wasn't completely visible because of overflow hidden in parent component, so added overflow-y-scroll instead
- also added session check, if user is already logged in, redirect to /mail/inbox
> fix: scroll-able home page and redirect user to /mail/inbox if already logged in 

- components/ui/nav-user.tsx
This PR migrates the user avatar implementation to use shadcn/ui's Avatar component, improving the handling of missing profile images while maintaining the existing layout and functionality. Fixes #262
- Replaced custom avatar implementation with shadcn/ui's `Avatar`, `AvatarImage`, and `AvatarFallback` components from https://ui.shadcn.com/docs/components/avatar
- Added proper fallback handling when user images are not available
- Fixed type errors related to null profile image values using nullish coalescing
- Maintained existing layout and responsive behavior
<table>
<tr>
<td>
<p>Before</p>
</td>
<td>
<p>After</p>
</td>
<td>
<p>Signed-in State</p>
</td>
</tr>
</table>
- Verified avatar displays correctly with:
- Valid profile pictures
- Missing profile pictures (shows initials)
- …
> Avatar Component Migration to shadcn/ui, fixes #262

- components/mail/mail-list.tsx
- components/ui/scroll-area.tsx
Basically radix-ui's ScrollArea primitives return a distinct type of scrollTop compared to regular div -> overflow-auto. 
hence when tanstack virtual tried to calculate the length(height) of current scroll, It failed to update, there by did not update (render) new items in the dom. 
Fix: the ref was moved to ScrollAreaPrimitive.Vieweport from ScrollAreaPrimitive.Root which returns required scrollTop
---
https://github.com/user-attachments/assets/c3d478d6-c5cc-4763-8510-c33354aeb7ba
Notice, the data-index of email threads are virtualized, meaning only the emails in the viewport are being rendered/added in the DOM
---
_By submitting …
> fix:new elements are not being rendered

- apps/mail/actions/ai-reply.ts
- apps/mail/app/(routes)/settings/general/page.tsx
- apps/mail/components/create/editor.tsx
- apps/mail/components/mail/mail-list.tsx
- apps/mail/components/mail/reply-composer.tsx
- apps/mail/locales/en.json
- packages/db/src/schema.ts
- packages/db/src/user_settings_default.ts
- AI Replier improved. you can hit tab to get the information now
- Better system prompt
> Improved ai with custom prompt

- apps/mail/lib/constants.ts
- apps/mail/providers/query-provider.tsx
recreate query client properly if session data changes, so the cache is properly tied to the account
---
---
> fix: recreate query client properly if session changes

- apps/mail/lib/hotkeys/mail-list-hotkeys.tsx
Improved mail list hotkey functionality by adding a `shouldUseHover` flag to determine when to use hover actions versus bulk selection actions.
- Added a `shouldUseHover` flag that checks if bulk selection is empty
- Updated hotkey handlers (markAsRead, markAsUnread, archiveEmail) to use this flag when determining whether to act on hovered email or selected emails
- Removed unused imports and functions:
- Removed `useQueryClient`, `useTRPC`, `useStats` imports
- Removed `refetch`, `mutateStats`, `invalidateCount` functions
- Removed a console.log statement in the selectAll function
- Updated dependency arrays in useCallback hooks to include the new `shouldUseHover` flag
1. Test mail list hotkeys with no emails selected:
- Hover over an email and use keyboard shortcuts to mark as …
> fixes issues with selected email optimistic updates

- apps/server/src/routes/agent/index.ts
- apps/server/wrangler.jsonc
This PR modifies the thread synchronization behavior by:
1. Setting `shouldDropTables` to `false` to prevent database tables from being dropped during sync operations
2. Making the `shouldLoop` variable read from the environment variable `THREAD_SYNC_LOOP` with a default of enabled
3. Updating the default value of `THREAD_SYNC_LOOP` to `true` in the wrangler configuration
4. Removing an unused import of `parseISO` from date-fns
These changes ensure that thread synchronization runs continuously by default while preserving database tables.
This change improves the reliability of thread synchronization by making it enabled by default and preventing accidental data loss from table drops.
---
_By submitting this pull request, I confirm that my contribution is made under the terms of the …
> dont drop tables

- apps/mail/components/context/thread-context.tsx
- apps/server/src/routes/agent/index.ts
- apps/server/src/routes/agent/rpc.ts
This PR implements thread deletion functionality, allowing users to permanently delete threads from the bin. The implementation includes:
1. Replacing the optimistic delete with a real deletion using TRPC mutation
2. Enabling the previously disabled delete button in the thread context menu
3. Adding server-side support for thread deletion from the database
4. Adding folder name normalization to handle 'bin' vs 'trash' naming differences
The implementation now properly deletes threads from the database when the user selects the delete option from the context menu. The UI provides toast notifications to indicate the deletion status.
> Implement thread deletion functionality
